version: '3'

services:
    web:
        container_name: django
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        working_dir: /code
        ports:
            - 18000:8000
        volumes:
            - ./django_practice:/code
        depends_on:
            - db
    db:
        container_name: mysql
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: django_docker
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306